Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "../demystify/__main__.py", line 124, in <module>
    explainer.init_from_essence(args.eprime, args.eprimeparam)
  File "/Users/matthewmcilree/URAS/Demystify/demystify/demystify/explain.py", line 48, in init_from_essence
    self.solution = self._get_puzzle_solution()
  File "/Users/matthewmcilree/URAS/Demystify/demystify/demystify/explain.py", line 306, in _get_puzzle_solution
    raise SolveError("Your problem has multiple solutions!")
demystify.explain.SolveError: Your problem has multiple solutions!
